// src/model/Corda.ts
export enum Corda {
  SEM_CORDA = "SEM_CORDA",
  AZUL = "AZUL",
  AZUL_MARROM = "AZUL_MARROM",
  MARROM = "MARROM",
  MARROM_VERDE = "MARROM_VERDE",
  VERDE = "VERDE",
  VERDE_AMARELA = "VERDE_AMARELA",
  AMARELA = "AMARELA",
  AMARELA_ROXA = "AMARELA_ROXA",
  ROXA = "ROXA",
  VERMELHA = "VERMELHA",
  BRANCA = "BRANCA",
}
