// src/model/Graduation.ts
export enum Graduation {
  ALUNO = "ALUNO",
  MONITOR = "MONITOR",
  IMPROVER = "IMPROVER",
  INSTRUCTOR = "INSTRUCTOR",
  CONTRAMESTRE = "CONTRAMESTRE",
  MESTRE_EDIFICADOR = "MESTRE_EDIFICADOR",
  MESTRE_DIGNIFICADOR = "MESTRE_DIGNIFICADOR",
  OTHER = "OTHER",
}
