export enum PaymentStatus {
  APPROVED = "APPROVED",
  DISAPPROVED = "DISAPPROVED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  CANCELED = "CANCELED",
  CANCELLATION_ANALYSIS = "CANCELLATION_ANALYSIS",
  EXPIRED = "EXPIRED",
}
